### ISSUE TITLE
Disable github actions

### ISSUE THREAD

**Issue by baentsch** [igorbarshteyn/oqs-openssl-quic#3]
Hi Igor, when adding the docker files for client & server side I noticed that github actions on this project are still enabled (and cause failures)... So what'd be your preference: a) Disable them altogether in the project settings (as done in oqs-openssl) or b) remove the workflow files (just added https://github.com/igorbarshteyn/oqs-openssl-quic/commit/2d3a5912975562cb51b836ea3d7a58d7e0b74046 to facilitate that) ?

**Comment by igorbarshteyn** [comment]
Hi Michael,

I'll disable github actions alltogether in project settings.

Let me figure out how to do that and I''ll do it ASAP (still new to github).

Thanks,

--Igor

**Comment by igorbarshteyn** [comment]
Done. Actions are disabled and no more workflows will run. Closing issue.
